version: '3.7'

services:
  mysql:
    platform: linux/amd64
    build:
      context: ./
      dockerfile : Mysql.Dockerfile
    container_name: mysql_server
    env_file: 
      - ./.env
      - ./env/.env.dev
      - ./env/.env.test
      - ./env/.env.production
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - server_network

  node:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Server.Dockerfile
    container_name: node_server
    restart: unless-stopped
    env_file: 
      - ./.env
      - ./env/.env.dev
      - ./env/.env.test
      - ./env/.env.production
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    networks:
      - server_network
volumes:
    db:
networks:
  server_network: