
services:
  mysql:
    image : ${DOCKER_USER_ID}/algorithm-mysql
    container_name: mysql_server
    env_file: 
      - ./.env
      - ./env/.env.production
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - server_network

  node:
    image: ${DOCKER_USER_ID}/algorithm-server
    container_name: node_server
    restart: unless-stopped
    env_file: 
      - ./.env
      - ./env/.env.production
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    networks:
      - server_network
volumes:
    db:
networks:
  server_network:


